openapi: 3.0.3
info:
  title: Specifiche Servizi FVOE e FVA - OpenAPI 3.0
  x-summary: >-
    Specifiche dei servizi esposti dalla Nuova Piattaforma Appalti (NPA) per l'accesso e la consultazione del FVOE e FVA
  description: |-
   Sono descritte le specifiche dei servizi esposti dalla Nuova Piattaforma Appalti (NPA) per l'accesso e la consultazione del Fascicolo Virtuale dell'Operatore Economico e del Fascicolo Virtuale dell'Appalto da parte della Stazione Appaltante. 
   
    #### Documentazione
    La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:
        [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md)

  # I termini del servizio.
  termsOfService: 'https://github.com/anticorruzione/npa/blob/main/README.md#termini-del-servizio'
  # Chi posso contattare per informazioni sul servizio e sul suo stato?
  contact:
    email: ufficio.uscp@anticorruzione.it
    name: ANAC - Ufficio Servizi IT Contratti Pubblici
    url: https://www.anticorruzione.it
  # L'audience delle API. Attualmente e' definito solamente
  #   la tipologia `public`.
  x-audience:
    - public
  # Ogni API deve avere un UUID, invariante nel tempo e
  #   rispetto al `title`.
  x-api-id: 08529555-7e06-4ad8-958a-6f03343ecbdb
  license:
    name: Licenza Pubblica dell'Unione Europea v. 1.2
    url: 'https://eupl.eu/1.2/it/'
  # Per dare indicazioni sul ciclo di vita dell'API
  # si puo' usare un parametro come:
  x-lifecycle:
    published: 2023-03-31
    maturity: published  
  version: 1.0.0
servers:
  - url: https://repositorydocument.swagger.io/api/v1
    description: Development server
tags:
  - name: SA
    description: Operazioni invocabili solo dalla SA
  - name: OE
    description: Operazioni invocabili solo dall'OE
  - name: serviziTecnici 
    description: Operazioni richiesti dalle linee guida sull'interoperabilità   
paths:
  /status:
    get:
      summary: Ritorna lo stato dell'applicazione. SINCRONO
      description: |
        Ritorna lo stato dell'applicazione. A scopo
        di test, su base randomica puo' ritornare
        un errore.
      operationId: idStatusShow
      tags:
        - serviziTecnici
      responses:
        '200':
            description: |
              Il server ha ritornato lo status. In caso di problemi
              ritorna sempre un problem+json.
              # Questi header di throttling sono obbligatori e definiti
              # nel Nuovo modello di interoperabilità.
            headers: &ratelimit_headers 
              X-RateLimit-Limit:
                 $ref: '#/components/headers/X-RateLimit-Limit'
              X-RateLimit-Remaining:
                 $ref: '#/components/headers/X-RateLimit-Remaining'
              X-RateLimit-Reset:
                 $ref: '#/components/headers/X-RateLimit-Reset'
            content:
              application/problem+json:
                schema:
                  $ref: '#/components/schemas/BaseResponse'
        '429':
            description: Limite di richieste raggiunto
            headers:
              Retry-After:
                $ref: '#/components/headers/Retry-After'
            content:
              application/problem+json:
                schema:
                  $ref: '#/components/schemas/BaseResponse'        
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BaseResponse'          
  /richiesta-accesso-fvoe:
    post:
      tags:
         - SA
      summary: API Rest per la creazione della richiesta di accesso al FVOE. ASINCRONO 
      description: Inserimento della richiesta di accesso ai documenti presenti nel FVOE. ASINCRONO 
      operationId: idAccessoRichiestaFVOE
      requestBody:
        description: Inserimento Richiesta di Accesso
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RichiestaAccessoRequest'
        required: true
      responses:
        '200':
          description: Operazione terminato con successo. Viene restituito l'idRichiesta generato da ANAC
          headers: *ratelimit_headers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RichiestaAccessoResponse'
          links:
            StatoRichiestaAccessoFVOEIdLink:  
              operationId: idAccessoVerificaRichiestaFVOE
              parameters:
                idRichiesta: '$response.body#/idRichiesta'
              description: >
                Il valore di `idRichiesta` restituito nella riposta può essere usato per richiamare `GET /verifica-richiesta-accesso`.  
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
  /verifica-richiesta-accesso-fvoe:
    get:
      tags:
        - SA
      summary: API Rest per verificare l'esito della richiesta di accesso. SINCRONO
      description: API Rest per il recupero dell'esito della richiesta di accesso. SINCRONO
      operationId: idAccessoVerificaRichiestaFVOE
      parameters:
        - in: query
          name: idRichiesta
          description: identificativo univoco della Richiesta di accesso definito da ANAC. (A UUID specified by RFC4122)
          schema:
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
      responses:
        '200':
          description: Operazione terminato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatoRichiestaResponse'
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
            $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
  /autorizza-accesso-fvoe:
    post:
      tags:
         - OE
      summary: API Rest per la conferma di accesso al FVOE. SINCRONO 
      description: Il servizio permette all'OE di autorizzare l'accesso al FVOE da parte della SA. SINCRONO 
      operationId: idAccessoAutorizza
      requestBody:
        description: Inserimento Autorizzazione 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutorizzaAccessoRequest'
        required: true
      responses:
        '200':
          description: Operazione terminato con successo. Viene restituito l'idAutorizzazione generato da ANAC
          headers: *ratelimit_headers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutorizzaAccessoResponse'
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
  /ricerca-documenti-fvoe:
    get:
      tags:
        - SA
        - OE
      summary: API Rest per la ricerca dei documenti di un FVOE. SINCRONO
      description: viene recuperata la lista con i dati di sintesi dei documenti presenti nel Fascicolo Virtuale dell'Operatore Economico. SINCRONO
      operationId: idDocumentiFVOERicerca
      parameters:
        - in: query  
          name: idFascicolo
          description: identificativo univoco del Fascicolo dell'OE
          schema:
            type: string
            example: "507f1f77bcf86cd799439011"
        - in: query
          name: dataInserimentoDa
          description: data di inserimento del documento - intervallo successivo (A datetime specified by RF3339)
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'
        - in: query
          name: dataInserimentoA
          description: data di inserimento del documento - intervallo precedente (A datetime specified by RF3339)
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'  
        - in: query
          name: dataEmissioneDa
          description: data di emissione del documento - intervallo successivo (A datetime specified by RF3339)
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'
        - in: query
          name: dataEmissioneA
          description: data di emissione del documento - intervallo precedente (A datetime specified by RF3339)
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'          
        - in: query
          name: dataFineValiditaDa
          description: data fine validità del documento - intervallo successivo (A datetime specified by RF3339)
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'
        - in: query
          name: dataFineValiditaA
          description: data fine validità del documento - intervallo precedente (A datetime specified by RF3339)
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'          
        - in: query
          name: numeroProtocollo
          description: numero di registrazione del documento
          schema:
            type: string
            example: '2342344342'
        - in: query
          name: dataProtocolloDa
          description: Data di protocollo dell'Documento - intervallo successivo (A datetime specified by RF3339)
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'
        - in: query
          name: dataProtocolloA
          description: Data di protocollo dell'Documento - intervallo precedente (A datetime specified by RF3339)
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'          
        - in: query
          name: dataCreazioneDa
          description: Data di creazione dell'Documento - intervallo successivo (A datetime specified by RF3339)
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'
        - in: query
          name: dataCreazioneA
          description: Data di creazione dell'Documento - intervallo precedente (A datetime specified by RF3339) 
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'  
        - in: query  
          name: stato  
          description: stato del documento
          schema:
            $ref: '#/components/schemas/StatoDocumentoEnum'
        - in: query  
          name: tipo  
          description: tipo del documento
          schema:
            $ref: '#/components/schemas/TipoDocumentoEnum'            
        - in: query
          name: page
          description: numero di pagine da visualizzare
          schema:
            type: integer
            format: int32
        - in: query  
          name: perPage
          description: numero di elementi per pagina
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Operazione terminato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentiListaResponse'
          links:
            RecuperaDocumentoFVOEIdLink:  
              operationId: idDocumentoFVOEDettaglio
              parameters:
                idDocumento: '$response.body#/result.idDocumento'
              description: >
                Il valore di `idDocumento` restituito nella riposta può essere usato per richiamare `GET /recupera-documento-fvoe`.        
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
  /recupera-documento-fvoe:
    get:
      tags:
        - SA
        - OE
      summary: API Rest per il recupero del documento dal FVOE. SINCRONO
      description: Viene resituita il Documento (Metadati e Binario). SINCRONO
      operationId: idDocumentoFVOEDettaglio
      parameters:
        - in: query
          name: idDocumento
          description: Identificato del Documento generato da ANAC
          schema:
            type: string
            example: "507f1f77bcf86cd799439011"
      responses:
        '200':
          description: Operazione terminato con successo. Viene restituito il Documento del Fascicolo Virtuale dell'Operatore Economico
          headers: *ratelimit_headers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecuperaDocumentoResponse'
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
            $ref: '#/components/responses/500InternalServerError'       
      security:
        - apiKeyAuth: []
  /richiedi-documento:
    get:
      tags:
        - SA
      summary: API Rest per la richiesta del documento agli enti certificatori. ASINCRONO - ASIMMETRICO
      description: viene richiesta la produzione di un nuovo documento agli enti certificatori.
         ASINCRONO - ASIMMETRICO
      operationId: idDocumentoRichiedi
      parameters:
        - in: query
          name: idFascicolo
          description: identificativo univoco del FVOE.
          required: true
          schema:
            type: string
            example: "507f1f77bcf86cd799439011"
        - in: query
          name: tipoDocumento
          description: tipologia del documento da richiedere.
          required: true
          schema:
            $ref: '#/components/schemas/TipoDocumentoEnum'
      responses:
        '200':
          description: Operazione terminato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RichiediDocumentoResponse'
          links:
            RecuperaDocumentoFVOEIdLink:  
              operationId: idDocumentoFVOEDettaglio
              parameters:
                idDocumento: '$response.body#/result.idDocumento'
              description: >
                Il valore di `idDocumento` restituito nella riposta può essere usato per richiamare `GET /recupera-documento-fvoe`.  
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
  /recupera-storico-documento-fvoe:
    get:
      tags:
        - SA
      summary: API Rest per il recupero dello storico di un documento del FVOE. SINCRONO
      description: viene resituito il dettaglio dello storico di un documento del FVOE.
      operationId: idStoricoDocumentoFVOEDettaglio
      parameters:
        - in: query
          name: idDocumento
          description: Identificato del Documento generato da ANAC
          schema:
            type: string
            example: "507f1f77bcf86cd799439011"
      responses:
        '200':
          description: Operazione terminato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsultaStoricoOEResponse'   
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
            $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
  /ricerca-documenti-fva:
    get:
      tags:
        -  SA
      summary: API Rest per la ricerca dei documenti di un Fascicolo Virtuale dell'Appalto. SINCRONO
      description: viene recuperata la lista con i dati di sintesi dei documenti presenti nel Fascicolo Virtuale dell'Appalto. SINCRONO
      operationId: idDocumentiFVARicerca
      parameters:
        - in: query
          name: codiceAppalto
          description: il codice dell'Appalto         
          schema:
            type: integer
            format: int32
        - in: query    
          name: idAppalto
          description: Identificativo univoco dell'Appalto definito da ANAC. Restituito dall'operazione di creazione Appalto. (A UUID specified by FC4122).
          schema:
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"  
        - in: query
          name: CIG
          description: Identificativo univoco Gara-Lotto rilasciato da ANAC
          schema:
            type: string
            example: 9050626CD6
        - in: query  
          name: idFascicolo
          description: identificativo univoco del Fascicolo dell'Appalto
          schema:
            type: string
            example: "507f1f77bcf86cd799439011"
        - in: query
          name: dataInserimentoDa
          description: data di inserimento del documento - intervallo successivo (A datetime specified by RF3339)
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'
        - in: query
          name: dataInserimentoA
          description: data di inserimento del documento - intervallo precedente (A datetime specified by RF3339)
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'  
        - in: query
          name: dataEmissioneDa
          description: data di emissione del documento - intervallo successivo (A datetime specified by RF3339)
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'
        - in: query
          name: dataEmissioneA
          description: data di emissione del documento - intervallo precedente (A datetime specified by RF3339)
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'          
        - in: query
          name: dataFineValiditaDa
          description: data fine validità del documento - intervallo successivo (A datetime specified by RF3339)
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'
        - in: query
          name: dataFineValiditaA
          description: data fine validità del documento - intervallo precedente (A datetime specified by RF3339)
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'          
        - in: query
          name: numeroProtocollo
          description: numero di registrazione del documento
          schema:
            type: string
            example: '2342344342'
        - in: query
          name: dataProtocolloDa
          description: Data di protocollo dell'Documento - intervallo successivo (A datetime specified by RF3339)
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'
        - in: query
          name: dataProtocolloA
          description: Data di protocollo dell'Documento - intervallo precedente (A datetime specified by RF3339)
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'          
        - in: query
          name: dataCreazioneDa
          description: Data di creazione dell'Documento - intervallo successivo (A datetime specified by RF3339)
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'
        - in: query
          name: dataCreazioneA
          description: Data di creazione dell'Documento - intervallo precedente (A datetime specified by RF3339) 
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z' 
        - in: query  
          name: stato  
          description: stato del documento
          schema:
            $ref: '#/components/schemas/StatoDocumentoEnum'
        - in: query  
          name: tipo  
          description: tipo del documento
          schema:
            $ref: '#/components/schemas/TipoDocumentoEnum' 
          example: 'VISURA_CAMERALE' 
        - in: query
          name: page
          description: numero di pagine da visualizzare
          schema:
            type: integer
            format: int32
        - in: query  
          name: perPage
          description: numero di elementi per pagina
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Operazione terminato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentiListaResponse' 
          links:
            RecuperaDocumentoFVAIdLink:  
              operationId: idDocumentoFVADettaglio
              parameters:
                idDocumento: '$response.body#/result.idDocumento'
              description: >
                Il valore di `idDocumento` restituito nella riposta può essere usato per richiamare `GET /recupera-documento-fva`.      
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
  /recupera-documento-fva:
    get:
      tags:
         - SA
      summary: API Rest per il recupero del documento dal Fascicolo Virtuale dell'Appalto. SINCRONO
      description: Viene resituita il Documento (Metadati e Binario). SINCRONO
      operationId: idDocumentoFVADettaglio
      parameters:
        - in: query
          name: idDocumento
          description: Identificato del Documento generato da ANAC
          schema:
            type: string
            example: "507f1f77bcf86cd799439011"
      responses:
        '200':
          description: Operazione terminato con successo. Viene restituito il Documento del Fascicolo Virtuale dell'Appalto
          headers: *ratelimit_headers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecuperaDocumentoResponse'
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
            $ref: '#/components/responses/500InternalServerError'       
      security:
        - apiKeyAuth: []
  /recupera-storico-documento-fva:
    get:
      tags:
        - SA
        - OE
      summary: API Rest per il recupero dello storico di un documento del Fascicolo Virtuale dell'Appalto. SINCRONO
      description: viene resituito il dettaglio dello storico di un documento del Fascicolo Virtuale dell'Appalto.
      operationId: idStoricoDocumentoFVADettaglio
      parameters:
        - in: query
          name: idDocumento
          description: Identificato del Documento generato da ANAC
          schema:
            type: string
            example: "507f1f77bcf86cd799439011"
      responses:
        '200':
          description: Operazione terminato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsultaStoricoAResponse'   
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
  /ricerca-fascicoli-fva:
    get:
      tags:
        -  SA
      summary: API Rest per la ricerca dei fascicoli degli appalti. SINCRONO
      description: viene recuperata la lista con i dati di sintesi dei FVA. SINCRONO
      operationId: idFascicoliRicerca
      parameters:
        - in: query
          name: codiceAppalto
          description: il codice dell'Appalto         
          schema:
            type: integer
            format: int32
        - in: query    
          name: idAppalto
          description: Identificativo univoco dell'Appalto definito da ANAC. (A UUID specified by FC4122).
          schema:
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"  
        - in: query
          name: CIG
          description: Identificativo univoco Gara-Lotto rilasciato da ANAC
          schema:
            type: string
            example: 9050626CD6
        - in: query
          name: dataCreazioneDa
          description: Data di crezione del Fascicolo - intervallo successivo (A datetime specified by RF3339)
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'
        - in: query
          name: dataCreazioneA
          description: Data di crezione del Fascicolo - intervallo precedente (A datetime specified by RF3339) 
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'  
        - in: query
          name: page
          description: numero di pagine da visualizzare
          schema:
            type: integer
            format: int32
        - in: query  
          name: perPage
          description: numero di elementi per pagina
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Operazione terminato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FVAListaResponse'          
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
  /recupera-fascicolo-fva:
    get:
      tags:
         - SA
      summary: API Rest per la consultazione delle informazioni di dettaglio di un Fascicolo Virtuale dell'Appalto. SINCRONO
      description: vengono restituite le informazioni di dettaglio di un Fascicolo Virtuale dell'Appalto. SINCRONO
      operationId: idFascicoloDettaglio
      parameters:
        - in: query
          name: idAppalto
          description: Id dell'Appalto, alternativo al CIG
          schema:
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
        - in: query
          name: CIG
          description: Identificativo univoco Gara-Lotto rilasciato da ANAC, alternativo all'idAppalto
          schema:
            type: string
            example: 9050626CD6
      responses:
        '200':
          description: Operazione terminato con successo. Viene restituito il Fascicolo dell'Appalto
          headers: *ratelimit_headers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecuperaFascicoloResponse'
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
            $ref: '#/components/responses/500InternalServerError'       
      security:
        - apiKeyAuth: []
  /recupera-storico-fascicolo-fva:
    get:
      tags:
        - SA
      summary: API Rest per il recupero dello storico di un FVA. SINCRONO
      description: viene resituito il dettaglio dello storico di FVA.
      operationId: idStoricoFascicoloFVADettaglio
      parameters:
        - in: query
          name: idDocumento
          description: Identificato del Documento generato da ANAC
          schema:
            type: string
            example: "507f1f77bcf86cd799439011"
      responses:
        '200':
          description: Operazione terminato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsultaStoricoFVAResponse'   
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
  /recupero-anagrafica-oe:
    get:
      tags:
        - SA
        - OE
      summary: API Rest per il recupero dell’anagrafica degli OE. SINCRONO
      description: vengono restituito i dati anagrafici dell'OE. SINCRONO
      operationId: idAnagraficaOERicerca
      parameters:
        - in: query    
          name: codiceFiscale
          description: Codice Fiscale OE.
          required: true
          schema:
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"  
      responses:
        '200':
          description: Operazione terminato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsultaAnagraficaOEResponse'          
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
            $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
components:
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
    Sunset:
      description: The Sunset HTTP response header field, indicates that a URI is likely
        to become unresponsive at a specified point in the future.  It also defines
        a sunset link relation type that allows linking to resources providing information
        about an upcoming resource or service sunset.
      schema:
        example: Sun, 06 Nov 1994 08:49:37 GMT
        externalDocs:
          url: https://tools.ietf.org/html/rfc7231#appendix-D
        format: HTTP-date
        maxLength: 30
        type: string
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer  
    X-Ratelimit-Used: 
      description: The number of requests used in the current period
      schema:
        type: integer
        format: int32      
  responses:
    200AckResponse:
      description: Richiesta accettata
      headers: *ratelimit_headers
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AckResponse'
    400BadRequest:
      description: Richiesta malformattata
      headers: *ratelimit_headers
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    404NotFound:
      description: Dato non trovato
      headers: *ratelimit_headers
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    429TooManyRequests:
      description: Limite di richieste raggiunto
      headers:
        Retry-After:
            $ref: '#/components/headers/Retry-After'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    500InternalServerError:
      description: Errore generico. Operazione terminato con errore. Viene restituito il dettaglio dell'errore
      headers: *ratelimit_headers
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    503ServiceUnavailable:
      description: Service Unavailable
      headers:
        Retry-After:
            $ref: '#/components/headers/Retry-After'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    default:
      description: |-
       Errore inatteso. Non ritornare informazioni
       sulla logica interna e/o non pertinenti all'interfaccia.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    StatoDocumentoEnum:
      $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml#/components/schemas/StatoDocumentoEnum'
    StatoRichiestaEnum:
      $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml#/components/schemas/StatoRichiestaEnum'
    TipoDocumentoEnum: 
      $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml#/components/schemas/TipoDocumentoEnum'
    AnagraficaOEType:
      $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml#/components/schemas/AnagraficaOEType' 
    FVOEType:
      $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml#/components/schemas/FVOEType' 
    FVAType:
      $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml#/components/schemas/FVAType'
    DocumentoType:
      $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml#/components/schemas/DocumentoType'
    DocumentoOEType:
      $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml#/components/schemas/DocumentoOEType'
    DocumentoAType:
      $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml#/components/schemas/DocumentoAType'
    ContentDocumentType:
      $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml#/components/schemas/ContentDocumentType' 
    AutorizzazioneAccessoType:
      $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml#/components/schemas/AutorizzazioneAccessoType' 
    RichiestaAccessoType:
      $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml#/components/schemas/RichiestaAccessoType'
    RichiestaAccessoRequest:
      allOf: # estende il modello dati RichiestaAccessoType
        - $ref: '#/components/schemas/RichiestaAccessoType'
      example:
        dataCreazione: "2022-01-23T12:02:05Z"
        dataScadenza: "2022-01-23T12:02:05Z"
        anagraficaOE:
            codice: "UI78588658"
        lottoType:
          CIG: "ACD4546346A"
    AutorizzaAccessoRequest:
      allOf: # estende il modello dati AutorizzaAccessoType
        - $ref: '#/components/schemas/AutorizzazioneAccessoType' 
      example:
        stato: "AUTORIZZATO"
        dataScadenza: "2022-01-23T12:02:05Z"
        richiestaAccesso: 
          idRichiesta: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"

    PaginazioneType:
      description: Oggetto per la paginazione dei risultati
      type: object
      additionalProperties: false
      properties:
        totRows: 
          description: Numero totale di record risultante dalla ricerca
          type: integer
          format: int32
        totPages: 
          description: Numero totale di pagine risultanti dalla ricerca
          type: integer
          format: int32      
        currentPage: 
          description: Numero di pagina corrente
          type: integer
          format: int32
        elementPage:
          description: Numero di elementi per pagina
          type: integer
          format: int32
    RichiestaAccessoResponse:
      allOf: # estende lo schema dati di BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      description: Risposta generica servizio
      type: object
      properties:
        idRichiesta:
          description: Identificativo univoco della richiesta definito da ANAC. (A UUID specified by RFC4122)
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
      example:
        detail: "Richiesta acquisita"
        status: 200
        title: "Operazione Effettuata" 
        idRichiesta: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"   
    AutorizzaAccessoResponse:
      allOf: # estende lo schema dati di BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      description: Risposta generica servizio
      type: object
      required:
        - idAutorizzazione
      properties:
        idAutorizzazione:
          description: Identificativo univoco dell'autorizzazione definito da ANAC. (A UUID specified by RFC4122)
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"      
    RecuperaDocumentoResponse :
      allOf: # estende lo schema dati di BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      properties:  
        document: 
          oneOf:
            - $ref: '#/components/schemas/DocumentoOEType'
            - $ref: '#/components/schemas/DocumentoAType'
          discriminator:
            propertyName: tipoOggetto
        content:
          $ref: '#/components/schemas/ContentDocumentType'
      example:
        status: 200
        title: "Operazione Effettuata"
        document:
          idDocument: "507f1f88bcf86cd987639011"
          tipoDcumento: "DURC"
          statoDocumento: "IN LAVORAZIONE"
          fascicoloOE:
            idFascicolo: "507f1f77bcf86cd799439011"
        content: 
          estensione: "PDF"
          size: 2313
          content: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
    RecuperaFascicoloResponse :
      allOf: # estende lo schema dati di BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      properties:
        fascicolo:
          oneOf:
            - $ref: '#/components/schemas/FVOEType'
            - $ref: '#/components/schemas/FVAType'
          discriminator:
            propertyName: tipoOggetto  
      example:
        status: 200
        title: "Operazione Effettuata"
        fascicolo:
          idFascicolo: "507f1f77hcf86cd799765676"
          stato: "IN LAVORAZIONE"
    ConsultaAnagraficaOEResponse :
      allOf: # estende lo schema dati di BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      properties:  
        anagrafica: 
          $ref: '#/components/schemas/AnagraficaOEType'
    RichiediDocumentoResponse:
      allOf: # estende lo schema dati di BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      properties:
        idRichiesta:
          description: Identificativo univoco della richiesta definito da ANAC. (A UUID specified by RFC4122)
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
      example:
        status: 200
        title: "Richiesta acquisita"
        idRichiesta: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
    StatoRichiestaResponse:
      allOf: # estende lo schema dati di BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      properties:
        stato:
          $ref: '#/components/schemas/StatoRichiestaEnum'
    FVAListaResponse :
      allOf: # estende la classe BaseResponse e PaginazioneType
        - $ref: '#/components/schemas/BaseResponse'
        - $ref: '#/components/schemas/PaginazioneType'
      description: Oggetto generico di ritorno di una risposta con paginazione
      type: object
      additionalProperties: false
      properties:
        result: 
          description: risposta di una lista di oggetti paginati specifica del servizio SINCRONO
          type: array
          items:
            $ref: '#/components/schemas/FVAType'        
    DocumentiListaResponse :
      allOf: # estende la classe BaseResponse e PaginazioneType
        - $ref: '#/components/schemas/BaseResponse'
        - $ref: '#/components/schemas/PaginazioneType'
      description: Oggetto generico di ritorno di una risposta con paginazione
      type: object
      additionalProperties: false
      properties:
        result: 
          description: risposta di una lista di oggetti paginati specifica del servizio SINCRONO
          type: array
          items:
            $ref: '#/components/schemas/DocumentoType'
      example:
        totRows: 2
        totPages: 1
        currentPage: 1
        elementPage": 2
        result: 
          - idDocument: "507f1f77bcf86cd799439011"
            tipoDcumento: "DURC"
            statoDocumento: "IN LAVORAZIONE"
            fascicoloOE: 
              idFascicolo: "507f1f77bcf86cd799439011"
          - idDocument: "507f1f77bcf86cd799888889"
            tipoDcumento: "DURC"
            statoDocumento: "IN LAVORAZIONE"
            fascicoloOE: 
              idFascicolo: "507f1f77cdf86cd799489011"
    ConsultaStoricoOEResponse:
      allOf: # estende lo schema dati di BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      properties:
        documenti:
          description: Lista documenti
          type: array
          items:
            $ref: '#/components/schemas/DocumentoOEType'
    ConsultaStoricoAResponse:
      allOf: # estende lo schema dati di BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      properties:
        documenti:
          description: Lista documenti
          type: array
          items:
            $ref: '#/components/schemas/DocumentoAType'
    ConsultaStoricoFVAResponse:
      allOf: # estende lo schema dati di BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      properties:
        documenti:
          description: Lista documenti
          type: array
          items:
            $ref: '#/components/schemas/FVAType'          
    BaseResponse:
      type: object
      additionalProperties: false
      properties:
          detail:
              description: |
                A human readable explanation specific to this occurrence of the
                problem.
              maxLength: 4096
              pattern: ^.{0,1024}$
              type: string
              example: 'Request took too long to complete.'
          instance:
              description: |
                An absolute URI that identifies the specific occurrence of the
                problem.
                It may or may not yield further information if dereferenced.
              format: uri
              maxLength: 2048
              type: string
          status:
              description: |
                The HTTP status code generated by the origin server for this
                occurrence
                of the problem.
              exclusiveMaximum: true
              format: int32
              maximum: 600
              minimum: 100
              type: integer
              example: 503
          title:
              description: |
                A short, summary of the problem type. Written in english and
                readable
                for engineers (usually not suited for non technical stakeholders
                and not localized);
              maxLength: 64
              pattern: ^[ -~]{0,64}$
              type: string
              example: 'Service Unavailable'
          type:
              description: |
                An absolute URI that identifies the problem type. When
                dereferenced,
                it SHOULD provide human-readable documentation for the problem
                type
                (e.g., using HTML).
              default: about:blank
              format: uri
              maxLength: 2048
              type: string
              example: 'https://tools.ietf.org/html/rfc7231#section-6.6.4'
          errori:
            description: elenco degli errori
            type: object
            properties:
              codice:
                type: string
                example: '001'
              descrizione:
                maxLength: 4096
                pattern: ^.{0,1024}$
                type: string
                example: 'Non è stato indicato il campo Motivazione richiesta CIG.'
    ErrorResponse:
      allOf: # estende la classe BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
    AckResponse:
      allOf: # estende la classe BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      example:
        status: 200
        title: "Richiesta acquisita"
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      name: apiKeyAuth # name of the header, query parameter or cookie
      in: header  # can be "header", "query" or "cookie"
